##################################################################
     ##  CV Boxplot to show the SLIDE model performance ##
##################################################################
```{r setup, include=FALSE}
library(ggplot2)
```

```{r load data}
# Define the path to the folders containing the .rds files
base_path <- "/ix/djishnu/Akanksha/datasets/ERCC1_KO/metacell/slide_outs/optimize_slide/female_0.1_spec/0.01_0.1_out/SLIDE_CV_replicate_data"  # Replace with the path to your directories
folders <- list.dirs(base_path, recursive = FALSE)

# Initialize an empty data frame to store the AUC values
auc_data <- data.frame(Method = character(), AUC = numeric(), stringsAsFactors = FALSE)
# Set a path to save the boxplot
pdf("/ix/djishnu/Akanksha/datasets/ERCC1_KO/metacell/slide_outs/optimize_slide/female_0.1_spec/0.01_0.1_out/SLIDE_CV_replicate_data/SLIDECV_Boxplot_females.pdf", height = 5, width = 5)

# Loop through each replicate folder
for (folder in folders) {
  # Get a list of .rds files in the current folder
  rds_files <- list.files(folder, pattern = "\\.rds$", full.names = TRUE)
  
  # Loop through each .rds file in the current folder
  for (file in rds_files) {
    # Load the .rds file
    result <- readRDS(file)
    
    # Extract AUC values for SLIDE and SLIDE_ys
    slide_auc <- result[["final_corr"]][result[["final_corr"]]$method == "SLIDE", "auc"]
    slide_y_auc <- result[["final_corr"]][result[["final_corr"]]$method == "SLIDE_y", "auc"]
    
    # Append to the data frame
    auc_data <- rbind(auc_data, data.frame(Method = "Actual", AUC = slide_auc))
    auc_data <- rbind(auc_data, data.frame(Method = "Permutation", AUC = slide_y_auc))
  }
}
```

``` {r plot}
# Create the plot and store it
p <- ggplot(auc_data, aes(x = Method, y = AUC, fill = Method)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "",
       x = "Method",
       y = "AUC") +
  scale_fill_manual(values = c("Actual" = "#007FFF", "Permutation" = "skyblue")) +
  theme(panel.grid = element_blank(), 
        axis.line.y = element_line(color = "black"),
        axis.ticks.y = element_line(color = "black"),
        axis.line.x = element_line(color = "black"),
        axis.ticks.x = element_line(color = "black"))

# Display it in RStudio
print(p)

# Save to PDF
ggsave("/ix/djishnu/Akanksha/datasets/ERCC1_KO/metacell/slide_outs/optimize_slide/female_0.1_spec/0.01_0.1_out/SLIDE_CV_replicate_data/SLIDECV_Boxplot_females.pdf", 
       plot = p, height = 5, width = 5)
```
